# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: React Dev Workflow

on:
  push:
    branches: [ dev ]
  #pull_request:
    #branches: [ dev ]

jobs:
  build-and-test:

    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./front-end-203

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: cd build && ls
    #- run: npm test
    #deploying steps to somewhere. TO be used next time.


    #temp upload files to verify builds
    - name: Save artifact
      uses: actions/upload-artifact@v3
      with:
        name: github-actions-artifact
        path: ./front-end-203/build
    
