# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: React Prod Workflow

on:
  push:
    branches: [main]
  #pull_request:
  #branches: [ dev ]

permissions: write-all

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./front-end-203

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "./front-end-203/package-lock.json"
      #- run: npm i -g npm@latest
      - run: npm ci
      - run: npm run build:prod --if-present
      - run: cd build && ls
      #- run: npm test
      #deploying steps to somewhere. TO be used next time.
      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build # The branch name where you want to push the assets
          FOLDER: front-end-203/build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub will automatically add this - you don't need to bother getting a token
          MESSAGE: "Build: ({sha}) {msg}" # The commit message

      #temp upload files to verify builds
      - name: Save artifact
        uses: actions/upload-artifact@v3
        with:
          name: github-actions-artifact
          path: ./front-end-203/build
